--------------------------------------------------------
--  파일이 생성됨 - 월요일-1월-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ORDER_SEQ
--------------------------------------------------------
   DROP SEQUENCE "ORDER_SEQ";
   CREATE SEQUENCE  "ORDER_SEQ"  MINVALUE 1 MAXVALUE 10 INCREMENT BY 3 START WITH 13 NOCACHE  NOORDER  CYCLE ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------
  DROP TABLE ORDER_LINE;
  DROP TABLE ORDER_INFO;
  DROP TABLE CUSTOMER;
  DROP TABLE PRODUCT;
  DROP TABLE ACCOUNT;

  CREATE TABLE "CUSTOMER" 
   (	"ID" VARCHAR2(5 BYTE), 
	"PWD" VARCHAR2(5 BYTE), 
	"NAME" VARCHAR2(15 BYTE), 
	"ZIPCODE" CHAR(5 BYTE), 
	"ADDR1" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PRODUCT" 
   (	"PROD_NO" VARCHAR2(5 BYTE), 
	"PROD_NAME" VARCHAR2(50 BYTE), 
	"PROD_PRICE" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_INFO
--------------------------------------------------------

  CREATE TABLE "ORDER_INFO" 
   (	"ORDER_NO" NUMBER, 
	"ORDER_ID" VARCHAR2(5 BYTE), 
	"ORDER_DT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_LINE
--------------------------------------------------------

  CREATE TABLE "ORDER_LINE" 
   (	"ORDER_NO" NUMBER, 
	"ORDER_PROD_NO" VARCHAR2(5 BYTE), 
	"ORDER_QUANTITY" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "ACCOUNT" 
   (	"NO" CHAR(3 BYTE), 
	"BALANCE" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View VW_ORDER
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VW_ORDER" ("no", "id", "name", "dt", "ORDER_PROD_NO", "PROD_NAME", "PROD_PRICE", "ORDER_QUANTITY") AS 
  SELECT info.order_no "no", order_id "id", c.name "name", order_dt "dt",
               line.order_prod_no, p.prod_name, p.prod_price, order_quantity
     FROM  order_info info JOIN customer c ON (info.order_id = c.id)
                               JOIN order_line line ON (info.order_no = line.order_no)
                               JOIN product p   ON (line.order_prod_no = p.prod_no)
;
REM INSERTING into CUSTOMER
SET DEFINE OFF;
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id2','p2','n2','12345','6층');
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id1','p1','n1','12345','유플렉스');
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id5','p5','n5',null,null);
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id3','p3','n3',null,null);
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id4','p4','n4','12345','KOSTA');
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id6','p6','n6',null,null);
Insert into CUSTOMER (ID,PWD,NAME,ZIPCODE,ADDR1) values ('id7','p7','n7',null,null);
REM INSERTING into PRODUCT
SET DEFINE OFF;
REM INSERTING into ORDER_INFO
SET DEFINE OFF;
Insert into ORDER_INFO (ORDER_NO,ORDER_ID,ORDER_DT) values (2,'id1',to_date('21/01/14','RR/MM/DD'));
REM INSERTING into ORDER_LINE
SET DEFINE OFF;
REM INSERTING into VW_ORDER
SET DEFINE OFF;
REM INSERTING into ACCOUNT
SET DEFINE OFF;
Insert into ACCOUNT (NO,BALANCE) values ('101',90);
Insert into ACCOUNT (NO,BALANCE) values ('202',110);
Insert into ACCOUNT (NO,BALANCE) values ('1  ',1);
--------------------------------------------------------
--  DDL for Index CUSTOMER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_ID_PK" ON "CUSTOMER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRODUCT_NO_PK" ON "PRODUCT" ("PROD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDER_INFO_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORDER_INFO_NO_PK" ON "ORDER_INFO" ("ORDER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDER_LINE_NO_PROD_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORDER_LINE_NO_PROD_NO_PK" ON "ORDER_LINE" ("ORDER_NO", "ORDER_PROD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_NO_PK" ON "ACCOUNT" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_PWD_CK" CHECK ( LENGTH(pwd) > 1) ENABLE;
  ALTER TABLE "CUSTOMER" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "CUSTOMER" ADD CONSTRAINT "CUSTOMER_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PRODUCT" ADD CONSTRAINT "PRODUCT_NO_PK" PRIMARY KEY ("PROD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PRODUCT" ADD CONSTRAINT "PRODUCT_PRICE_CK" CHECK (prod_price >= 0) ENABLE;
  ALTER TABLE "PRODUCT" MODIFY ("PROD_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_INFO
--------------------------------------------------------

  ALTER TABLE "ORDER_INFO" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "ORDER_INFO" ADD CONSTRAINT "ORDER_INFO_NO_PK" PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDER_LINE
--------------------------------------------------------

  ALTER TABLE "ORDER_LINE" ADD CONSTRAINT "ORDER_LINE_NO_PROD_NO_PK" PRIMARY KEY ("ORDER_NO", "ORDER_PROD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ORDER_LINE" ADD CONSTRAINT "ORDER_LINE_QUANTITY_CK" CHECK (order_quantity > 0) ENABLE;
  ALTER TABLE "ORDER_LINE" MODIFY ("ORDER_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ORDER_LINE" MODIFY ("ORDER_PROD_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "ACCOUNT" ADD CONSTRAINT "ACCOUNT_NO_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ACCOUNT" MODIFY ("BALANCE" NOT NULL ENABLE);
